In [2]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in ./.local/lib/python3.10/site-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in ./.local/lib/python3.10/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/tljh/user/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/tljh/user/lib/python3.10/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in ./.local/lib/python3.10/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /opt/tljh/user/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [9]:
import pandas as pd

census_df_raw = pd.read_csv("shared_data_read_only/Census-Data/ACSST5Y2022.S2201-Data.csv")
census_meta_df_raw = pd.read_csv("shared_data_read_only/Census-Data/ACSST5Y2022.S2201-Column-Metadata.csv")

/tmp/ipykernel_23627/3525896953.py:3: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,70,71,72,73,74,75,76,77,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,222,223,224,225,226,227,228,229,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,374,375,376,377,378,379,380,381) have mixed types. Specify dtype option on import or set low_memory=False.
  census_df_raw = pd.read_csv("shared_data_read_only/Census-Data/ACSST5Y2022.S2201-Data.csv")

In [10]:
census_meta_df = census_meta_df_raw[~census_meta_df_raw["Label"].str.contains("Margin")]
census_meta_df = census_meta_df[~census_meta_df["Label"].str.contains("60 years")]
census_meta_df = census_meta_df[~census_meta_df["Label"].str.contains("Percent")]
census_meta_df = census_meta_df[(~census_meta_df["Label"].str.contains("Hispanic")) & (~census_meta_df["Label"].str.contains("SNAP"))]
census_meta_df = census_meta_df[(~census_meta_df["Label"].str.contains("Hispanic")) & (~census_meta_df["Label"].str.contains("SNAP"))]

census_meta_df.shape

census_meta_df

       Column Name                                              Label
0           GEO_ID                                          Geography
1             NAME                               Geographic Area Name
2   S2201_C01_001E                        Estimate!!Total!!Households
8   S2201_C01_004E  Estimate!!Total!!Households!!Married-couple fa...
10  S2201_C01_005E         Estimate!!Total!!Households!!Other family:
12  S2201_C01_006E  Estimate!!Total!!Households!!Other family:!!Ma...
14  S2201_C01_007E  Estimate!!Total!!Households!!Other family:!!Fe...
16  S2201_C01_008E  Estimate!!Total!!Households!!Nonfamily households
18  S2201_C01_009E  Estimate!!Total!!Households!!With children und...
20  S2201_C01_010E  Estimate!!Total!!Households!!With children und...
22  S2201_C01_011E  Estimate!!Total!!Households!!With children und...
24  S2201_C01_012E  Estimate!!Total!!Households!!With children und...
26  S2201_C01_013E  Estimate!!Total!!Households!!With children und...
28  S2201_C01_014E  Estimate!!Total!!Households!!With children und...
30  S2201_C01_015E  Estimate!!Total!!Households!!No children under...
32  S2201_C01_016E  Estimate!!Total!!Households!!No children under...
34  S2201_C01_017E  Estimate!!Total!!Households!!No children under...
36  S2201_C01_018E  Estimate!!Total!!Households!!No children under...
38  S2201_C01_019E  Estimate!!Total!!Households!!No children under...
40  S2201_C01_020E  Estimate!!Total!!Households!!No children under...
42  S2201_C01_021E  Estimate!!Total!!Households!!POVERTY STATUS IN...
44  S2201_C01_022E  Estimate!!Total!!Households!!POVERTY STATUS IN...
46  S2201_C01_023E  Estimate!!Total!!Households!!DISABILITY STATUS...
48  S2201_C01_024E  Estimate!!Total!!Households!!DISABILITY STATUS...
50  S2201_C01_025E  Estimate!!Total!!Households!!RACE AND HISPANIC...
52  S2201_C01_026E  Estimate!!Total!!Households!!RACE AND HISPANIC...
54  S2201_C01_027E  Estimate!!Total!!Households!!RACE AND HISPANIC...
56  S2201_C01_028E  Estimate!!Total!!Households!!RACE AND HISPANIC...
58  S2201_C01_029E  Estimate!!Total!!Households!!RACE AND HISPANIC...
60  S2201_C01_030E  Estimate!!Total!!Households!!RACE AND HISPANIC...
62  S2201_C01_031E  Estimate!!Total!!Households!!RACE AND HISPANIC...
68  S2201_C01_034E  Estimate!!Total!!Households!!HOUSEHOLD INCOME ...
70  S2201_C01_035E             Estimate!!Total!!WORK STATUS!!Families
72  S2201_C01_036E  Estimate!!Total!!WORK STATUS!!Families!!No wor...
74  S2201_C01_037E  Estimate!!Total!!WORK STATUS!!Families!!1 work...
76  S2201_C01_038E  Estimate!!Total!!WORK STATUS!!Families!!2 or m...

In [32]:
import pandas as pd

# Assuming saved_census_df_raw is your DataFrame
# Filter rows where 'NAME' contains 'Philadelphia' (case insensitive)
philadelphia_df = saved_census_df_raw[saved_census_df_raw['NAME'].str.contains('Philadelphia', case=False)]

# Display the DataFrame with rows containing 'Philadelphia'
philadelphia_df

,GEO_ID,NAME,S2201_C01_001E,S2201_C01_002E,S2201_C01_003E,S2201_C01_004E,S2201_C01_005E,S2201_C01_006E,S2201_C01_007E,S2201_C01_008E,...,S2201_C06_029E,S2201_C06_030E,S2201_C06_031E,S2201_C06_032E,S2201_C06_033E,S2201_C06_034E,S2201_C06_035E,S2201_C06_036E,S2201_C06_037E,S2201_C06_038E
65977,1400000US42101000101,Census Tract 1.01; Philadelphia County; Pennsy...,1413,201,1212,268,56,15,41,1089,...,0.0,7.1,3.6,12.8,76.5,(X),(X),4.9,12.0,83.0
65978,1400000US42101000102,Census Tract 1.02; Philadelphia County; Pennsy...,1960,265,1695,359,29,0,29,1572,...,0.0,2.5,1.4,5.3,84.0,(X),(X),6.7,11.3,82.0
65979,1400000US42101000200,Census Tract 2; Philadelphia County; Pennsylvania,1686,412,1274,474,161,76,85,1051,...,0.0,0.0,6.1,7.2,51.7,(X),(X),12.9,2.6,84.5
65980,1400000US42101000300,Census Tract 3; Philadelphia County; Pennsylvania,2347,923,1424,527,25,6,19,1795,...,0.0,2.5,12.7,7.2,53.3,(X),(X),17.5,26.7,55.9
65981,1400000US42101000401,Census Tract 4.01; Philadelphia County; Pennsy...,1957,511,1446,331,76,50,26,1550,...,0.0,0.9,5.7,5.0,55.7,(X),(X),0.0,46.9,53.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66380,1400000US42101980905,Census Tract 9809.05; Philadelphia County; Pen...,0,0,0,0,0,0,0,0,...,-,-,-,-,-,(X),(X),-,-,-
66381,1400000US42101980906,Census Tract 9809.06; Philadelphia County; Pen...,0,0,0,0,0,0,0,0,...,-,-,-,-,-,(X),(X),-,-,-
66382,1400000US42101989100,Census Tract 9891; Philadelphia County; Pennsy...,0,0,0,0,0,0,0,0,...,-,-,-,-,-,(X),(X),-,-,-
66383,1400000US42101989200,Census Tract 9892; Philadelphia County; Pennsy...,0,0,0,0,0,0,0,0,...,-,-,-,-,-,(X),(X),-,-,-
66384,1400000US42101989300,Census Tract 9893; Philadelphia County; Pennsy...,0,0,0,0,0,0,0,0,...,-,-,-,-,-,(X),(X),-,-,-

In [30]:
philadelphia_df

Empty DataFrame
Columns: [GEO_ID, NAME, S2201_C01_001E, S2201_C01_002E, S2201_C01_003E, S2201_C01_004E, S2201_C01_005E, S2201_C01_006E, S2201_C01_007E, S2201_C01_008E, S2201_C01_009E, S2201_C01_010E, S2201_C01_011E, S2201_C01_012E, S2201_C01_013E, S2201_C01_014E, S2201_C01_015E, S2201_C01_016E, S2201_C01_017E, S2201_C01_018E, S2201_C01_019E, S2201_C01_020E, S2201_C01_021E, S2201_C01_022E, S2201_C01_023E, S2201_C01_024E, S2201_C01_025E, S2201_C01_026E, S2201_C01_027E, S2201_C01_028E, S2201_C01_029E, S2201_C01_030E, S2201_C01_031E, S2201_C01_032E, S2201_C01_033E, S2201_C01_034E, S2201_C01_035E, S2201_C01_036E, S2201_C01_037E, S2201_C01_038E, S2201_C02_001E, S2201_C02_002E, S2201_C02_003E, S2201_C02_004E, S2201_C02_005E, S2201_C02_006E, S2201_C02_007E, S2201_C02_008E, S2201_C02_009E, S2201_C02_010E, S2201_C02_011E, S2201_C02_012E, S2201_C02_013E, S2201_C02_014E, S2201_C02_015E, S2201_C02_016E, S2201_C02_017E, S2201_C02_018E, S2201_C02_019E, S2201_C02_020E, S2201_C02_021E, S2201_C02_022E, S2201_C02_023E, S2201_C02_024E, S2201_C02_025E, S2201_C02_026E, S2201_C02_027E, S2201_C02_028E, S2201_C02_029E, S2201_C02_030E, S2201_C02_031E, S2201_C02_032E, S2201_C02_033E, S2201_C02_034E, S2201_C02_035E, S2201_C02_036E, S2201_C02_037E, S2201_C02_038E, S2201_C03_001E, S2201_C03_002E, S2201_C03_003E, S2201_C03_004E, S2201_C03_005E, S2201_C03_006E, S2201_C03_007E, S2201_C03_008E, S2201_C03_009E, S2201_C03_010E, S2201_C03_011E, S2201_C03_012E, S2201_C03_013E, S2201_C03_014E, S2201_C03_015E, S2201_C03_016E, S2201_C03_017E, S2201_C03_018E, S2201_C03_019E, S2201_C03_020E, S2201_C03_021E, S2201_C03_022E, ...]
Index: []

[0 rows x 230 columns]

In [35]:
import pandas as pd

# Assuming saved_census_df_raw is your DataFrame
# Filter rows where 'NAME' contains 'Philadelphia' (case insensitive)
philadelphia_df = saved_census_df_raw[saved_census_df_raw['NAME'].str.contains('Philadelphia', case=False)]

# Filter rows where 'S2201_C01_001E' is not equal to 0
philadelphia_df_filtered = philadelphia_df[philadelphia_df['S2201_C01_001E'] != 0]

# Display the filtered DataFrame
philadelphia_df_filtered

,GEO_ID,NAME,S2201_C01_001E,S2201_C01_002E,S2201_C01_003E,S2201_C01_004E,S2201_C01_005E,S2201_C01_006E,S2201_C01_007E,S2201_C01_008E,...,S2201_C06_029E,S2201_C06_030E,S2201_C06_031E,S2201_C06_032E,S2201_C06_033E,S2201_C06_034E,S2201_C06_035E,S2201_C06_036E,S2201_C06_037E,S2201_C06_038E
65977,1400000US42101000101,Census Tract 1.01; Philadelphia County; Pennsy...,1413,201,1212,268,56,15,41,1089,...,0.0,7.1,3.6,12.8,76.5,(X),(X),4.9,12.0,83.0
65978,1400000US42101000102,Census Tract 1.02; Philadelphia County; Pennsy...,1960,265,1695,359,29,0,29,1572,...,0.0,2.5,1.4,5.3,84.0,(X),(X),6.7,11.3,82.0
65979,1400000US42101000200,Census Tract 2; Philadelphia County; Pennsylvania,1686,412,1274,474,161,76,85,1051,...,0.0,0.0,6.1,7.2,51.7,(X),(X),12.9,2.6,84.5
65980,1400000US42101000300,Census Tract 3; Philadelphia County; Pennsylvania,2347,923,1424,527,25,6,19,1795,...,0.0,2.5,12.7,7.2,53.3,(X),(X),17.5,26.7,55.9
65981,1400000US42101000401,Census Tract 4.01; Philadelphia County; Pennsy...,1957,511,1446,331,76,50,26,1550,...,0.0,0.9,5.7,5.0,55.7,(X),(X),0.0,46.9,53.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66361,1400000US42101039001,Census Tract 390.01; Philadelphia County; Penn...,1269,374,895,306,650,78,572,313,...,0.0,0.8,17.8,24.9,21.8,(X),(X),5.3,50.2,44.5
66362,1400000US42101039002,Census Tract 390.02; Philadelphia County; Penn...,1721,953,768,348,990,482,508,383,...,0.0,0.0,27.5,39.0,14.1,(X),(X),4.0,65.4,30.5
66363,1400000US42101039100,Census Tract 391; Philadelphia County; Pennsyl...,1162,230,932,119,697,95,602,346,...,0.0,0.0,4.9,3.0,0.0,(X),(X),0.0,61.0,39.0
66367,1400000US42101980100,Census Tract 9801; Philadelphia County; Pennsy...,75,16,59,59,0,0,0,16,...,0.0,0.0,6.7,0.0,86.7,(X),(X),0.0,0.0,100.0
66368,1400000US42101980200,Census Tract 9802; Philadelphia County; Pennsy...,13,0,13,13,0,0,0,0,...,0.0,0.0,0.0,100.0,0.0,(X),(X),0.0,0.0,100.0

In [44]:
# Assuming philadelphia_df_filtered is your filtered DataFrame
# Save the filtered DataFrame to a CSV file
file_path = 'philadelphia_filtered.csv'
philadelphia_df_filtered.to_csv('phs.csv', index=False)

# Track the file location
print(f"Filtered data saved to: {'phs.csv'}")

Filtered data saved to: phs.csv

In [42]:
philadelphia_df_filtered

,GEO_ID,NAME,S2201_C01_001E,S2201_C01_002E,S2201_C01_003E,S2201_C01_004E,S2201_C01_005E,S2201_C01_006E,S2201_C01_007E,S2201_C01_008E,...,S2201_C06_029E,S2201_C06_030E,S2201_C06_031E,S2201_C06_032E,S2201_C06_033E,S2201_C06_034E,S2201_C06_035E,S2201_C06_036E,S2201_C06_037E,S2201_C06_038E
65977,1400000US42101000101,Census Tract 1.01; Philadelphia County; Pennsy...,1413,201,1212,268,56,15,41,1089,...,0.0,7.1,3.6,12.8,76.5,(X),(X),4.9,12.0,83.0
65978,1400000US42101000102,Census Tract 1.02; Philadelphia County; Pennsy...,1960,265,1695,359,29,0,29,1572,...,0.0,2.5,1.4,5.3,84.0,(X),(X),6.7,11.3,82.0
65979,1400000US42101000200,Census Tract 2; Philadelphia County; Pennsylvania,1686,412,1274,474,161,76,85,1051,...,0.0,0.0,6.1,7.2,51.7,(X),(X),12.9,2.6,84.5
65980,1400000US42101000300,Census Tract 3; Philadelphia County; Pennsylvania,2347,923,1424,527,25,6,19,1795,...,0.0,2.5,12.7,7.2,53.3,(X),(X),17.5,26.7,55.9
65981,1400000US42101000401,Census Tract 4.01; Philadelphia County; Pennsy...,1957,511,1446,331,76,50,26,1550,...,0.0,0.9,5.7,5.0,55.7,(X),(X),0.0,46.9,53.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66380,1400000US42101980905,Census Tract 9809.05; Philadelphia County; Pen...,0,0,0,0,0,0,0,0,...,-,-,-,-,-,(X),(X),-,-,-
66381,1400000US42101980906,Census Tract 9809.06; Philadelphia County; Pen...,0,0,0,0,0,0,0,0,...,-,-,-,-,-,(X),(X),-,-,-
66382,1400000US42101989100,Census Tract 9891; Philadelphia County; Pennsy...,0,0,0,0,0,0,0,0,...,-,-,-,-,-,(X),(X),-,-,-
66383,1400000US42101989200,Census Tract 9892; Philadelphia County; Pennsy...,0,0,0,0,0,0,0,0,...,-,-,-,-,-,(X),(X),-,-,-
66384,1400000US42101989300,Census Tract 9893; Philadelphia County; Pennsy...,0,0,0,0,0,0,0,0,...,-,-,-,-,-,(X),(X),-,-,-

In [45]:
zip_code = pd.read_csv("ziptotract.csv")

In [46]:
zip_code

,Unnamed: 0,ZIP,TRACT,USPS_ZIP_PREF_CITY,USPS_ZIP_PREF_STATE,RES_RATIO,BUS_RATIO,OTH_RATIO,TOT_RATIO
0,0,501,36103158607,HOLTSVILLE,NY,0.000000,1.000000,0.000000,1.000000
1,1,601,72001956800,ADJUNTAS,PR,0.014530,0.012469,0.042683,0.015121
2,2,601,72113071700,ADJUNTAS,PR,0.158291,0.199501,0.128049,0.160094
3,3,601,72001956600,ADJUNTAS,PR,0.180513,0.351621,0.378049,0.196259
4,4,601,72001956700,ADJUNTAS,PR,0.646667,0.436409,0.451220,0.628527
...,...,...,...,...,...,...,...,...,...
188841,188841,99925,2198000200,KLAWOCK,AK,1.000000,0.000000,1.000000,1.000000
188842,188842,99926,2198940100,METLAKATLA,AK,1.000000,0.000000,1.000000,1.000000
188843,188843,99927,2198000100,POINT BAKER,AK,0.000000,0.000000,1.000000,1.000000
188844,188844,99928,2130000101,WARD COVE,AK,0.000000,0.000000,1.000000,1.000000
188845,188845,99929,2275000300,WRANGELL,AK,1.000000,1.000000,1.000000,1.000000

In [47]:
# Filter rows where 'USPS_ZIP_PREF_CITY' is "PHILADELPHIA" and 'USPS_ZIP_PREF_STATE' is "PA"
zip_pa = zip_code[(zip_code['USPS_ZIP_PREF_CITY'] == "PHILADELPHIA") & (zip_code['USPS_ZIP_PREF_STATE'] == "PA")]

# Display the filtered DataFrame
zip_pa

,Unnamed: 0,ZIP,TRACT,USPS_ZIP_PREF_CITY,USPS_ZIP_PREF_STATE,RES_RATIO,BUS_RATIO,OTH_RATIO,TOT_RATIO
32376,32376,19101,42101036902,PHILADELPHIA,PA,1.000000,1.000000,1.000000,1.000000
32377,32377,19102,42101001101,PHILADELPHIA,PA,0.000158,0.000999,0.011940,0.001223
32378,32378,19102,42101000806,PHILADELPHIA,PA,0.331541,0.303545,0.246269,0.318955
32379,32379,19102,42101001204,PHILADELPHIA,PA,0.146947,0.017474,0.202985,0.122290
32380,32380,19102,42101000300,PHILADELPHIA,PA,0.164821,0.074388,0.105970,0.140300
...,...,...,...,...,...,...,...,...,...
33057,33057,19160,42101989300,PHILADELPHIA,PA,1.000000,1.000000,1.000000,1.000000
33058,33058,19172,42101001001,PHILADELPHIA,PA,0.000000,1.000000,0.000000,1.000000
33059,33059,19176,42101980901,PHILADELPHIA,PA,0.000000,1.000000,1.000000,1.000000
33060,33060,19181,42101000101,PHILADELPHIA,PA,0.000000,1.000000,0.000000,1.000000
33061,33061,19192,42101000403,PHILADELPHIA,PA,0.000000,1.000000,1.000000,1.000000

In [49]:
# Filter rows where 'USPS_ZIP_PREF_CITY' is "PHILADELPHIA" and 'USPS_ZIP_PREF_STATE' is "PA"
zip_pa = zip_code[(zip_code['USPS_ZIP_PREF_CITY'] == "PHILADELPHIA") & (zip_code['USPS_ZIP_PREF_STATE'] == "PA")]

# Select specific columns
philadelphia_zip_codes_filtered = zip_pa[['ZIP', 'TRACT', 'USPS_ZIP_PREF_STATE', 'USPS_ZIP_PREF_CITY']]

# Display the filtered DataFrame
philadelphia_zip_codes_filtered

         ZIP        TRACT USPS_ZIP_PREF_STATE USPS_ZIP_PREF_CITY
32376  19101  42101036902                  PA       PHILADELPHIA
32377  19102  42101001101                  PA       PHILADELPHIA
32378  19102  42101000806                  PA       PHILADELPHIA
32379  19102  42101001204                  PA       PHILADELPHIA
32380  19102  42101000300                  PA       PHILADELPHIA
...      ...          ...                 ...                ...
33057  19160  42101989300                  PA       PHILADELPHIA
33058  19172  42101001001                  PA       PHILADELPHIA
33059  19176  42101980901                  PA       PHILADELPHIA
33060  19181  42101000101                  PA       PHILADELPHIA
33061  19192  42101000403                  PA       PHILADELPHIA

[686 rows x 4 columns]

In [51]:
# Save the filtered DataFrame to a CSV file
file_path = 'zip_pa.csv'
philadelphia_zip_codes_filtered.to_csv('zip_pa.csv', index=False)

# Track the file location
print(f"Filtered data saved to: {'zip_pa.csv'}")

Filtered data saved to: zip_pa.csv

In [53]:
# Assuming philadelphia_df_filtered is your filtered DataFrame
# Save the filtered DataFrame to a CSV file
file_path = 'phs.csv'
philadelphia_df_filtered.to_csv(file_path, index=False)

# Track the file location
print(f"Filtered data saved to: {file_path}")

# Rename the 'GEOID' column to 'TRACT' in the filtered DataFrame
filtered_df.rename(columns={'GEO_ID': 'TRACT'}, inplace=True)

# Display the DataFrame with the renamed column
filtered_df

Filtered data saved to: phs.csv

/tmp/ipykernel_23627/429270171.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df.rename(columns={'GEO_ID': 'TRACT'}, inplace=True)

,TRACT,NAME,S2201_C01_001E,S2201_C01_002E,S2201_C01_003E,S2201_C01_004E,S2201_C01_005E,S2201_C01_006E,S2201_C01_007E,S2201_C01_008E,...,S2201_C06_029E,S2201_C06_030E,S2201_C06_031E,S2201_C06_032E,S2201_C06_033E,S2201_C06_034E,S2201_C06_035E,S2201_C06_036E,S2201_C06_037E,S2201_C06_038E
0,Geography,Geographic Area Name,Estimate!!Total!!Households,Estimate!!Total!!Households!!With one or more ...,Estimate!!Total!!Households!!No people in the ...,Estimate!!Total!!Households!!Married-couple fa...,Estimate!!Total!!Households!!Other family:,Estimate!!Total!!Households!!Other family:!!Ma...,Estimate!!Total!!Households!!Other family:!!Fe...,Estimate!!Total!!Households!!Nonfamily households,...,Estimate!!Percent households not receiving foo...,Estimate!!Percent households not receiving foo...,Estimate!!Percent households not receiving foo...,Estimate!!Percent households not receiving foo...,Estimate!!Percent households not receiving foo...,Estimate!!Percent households not receiving foo...,Estimate!!Percent households not receiving foo...,Estimate!!Percent households not receiving foo...,Estimate!!Percent households not receiving foo...,Estimate!!Percent households not receiving foo...
1,1400000US01001020100,Census Tract 201; Autauga County; Alabama,700,323,377,444,96,15,81,160,...,0.0,0.4,4.7,12.1,61.7,(X),(X),19.2,24.5,56.3
2,1400000US01001020200,Census Tract 202; Autauga County; Alabama,544,298,246,154,197,66,131,193,...,0.0,0.0,3.8,0.0,45.9,(X),(X),7.2,38.6,54.3
3,1400000US01001020300,Census Tract 203; Autauga County; Alabama,1305,565,740,569,351,61,290,385,...,0.0,1.4,0.0,1.4,75.7,(X),(X),10.1,28.6,61.2
4,1400000US01001020400,Census Tract 204; Autauga County; Alabama,1666,948,718,1048,188,29,159,430,...,0.0,0.0,5.3,0.8,88.8,(X),(X),27.1,34.4,38.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85392,1400000US72153750501,Census Tract 7505.01; Yauco Municipio; Puerto ...,1661,1052,609,562,424,29,395,675,...,0.0,10.7,10.6,100.0,0.0,(X),(X),34.2,29.0,36.7
85393,1400000US72153750502,Census Tract 7505.02; Yauco Municipio; Puerto ...,895,394,501,266,331,68,263,298,...,0.0,16.5,15.8,100.0,0.0,(X),(X),42.0,32.0,26.0
85394,1400000US72153750503,Census Tract 7505.03; Yauco Municipio; Puerto ...,685,402,283,227,181,7,174,277,...,0.0,17.5,5.0,100.0,0.0,(X),(X),34.1,26.6,39.3
85395,1400000US72153750601,Census Tract 7506.01; Yauco Municipio; Puerto ...,1557,776,781,732,295,64,231,530,...,0.0,16.2,13.2,98.9,0.0,(X),(X),21.6,38.8,39.6
85396,1400000US72153750602,Census Tract 7506.02; Yauco Municipio; Puerto ...,898,686,212,437,139,12,127,322,...,0.0,24.5,8.0,100.0,0.0,(X),(X),43.8,44.3,11.9

In [55]:
# Remove '1400000US' prefix from the 'TRACT' column in the filtered DataFrame
filtered_df['TRACT'] = filtered_df['TRACT'].str.replace('1400000US', '')

# Display the DataFrame with the updated 'TRACT' column
filtered_df

/tmp/ipykernel_23627/3138309877.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['TRACT'] = filtered_df['TRACT'].str.replace('1400000US', '')

,TRACT,NAME,S2201_C01_001E,S2201_C01_002E,S2201_C01_003E,S2201_C01_004E,S2201_C01_005E,S2201_C01_006E,S2201_C01_007E,S2201_C01_008E,...,S2201_C06_029E,S2201_C06_030E,S2201_C06_031E,S2201_C06_032E,S2201_C06_033E,S2201_C06_034E,S2201_C06_035E,S2201_C06_036E,S2201_C06_037E,S2201_C06_038E
0,Geography,Geographic Area Name,Estimate!!Total!!Households,Estimate!!Total!!Households!!With one or more ...,Estimate!!Total!!Households!!No people in the ...,Estimate!!Total!!Households!!Married-couple fa...,Estimate!!Total!!Households!!Other family:,Estimate!!Total!!Households!!Other family:!!Ma...,Estimate!!Total!!Households!!Other family:!!Fe...,Estimate!!Total!!Households!!Nonfamily households,...,Estimate!!Percent households not receiving foo...,Estimate!!Percent households not receiving foo...,Estimate!!Percent households not receiving foo...,Estimate!!Percent households not receiving foo...,Estimate!!Percent households not receiving foo...,Estimate!!Percent households not receiving foo...,Estimate!!Percent households not receiving foo...,Estimate!!Percent households not receiving foo...,Estimate!!Percent households not receiving foo...,Estimate!!Percent households not receiving foo...
1,01001020100,Census Tract 201; Autauga County; Alabama,700,323,377,444,96,15,81,160,...,0.0,0.4,4.7,12.1,61.7,(X),(X),19.2,24.5,56.3
2,01001020200,Census Tract 202; Autauga County; Alabama,544,298,246,154,197,66,131,193,...,0.0,0.0,3.8,0.0,45.9,(X),(X),7.2,38.6,54.3
3,01001020300,Census Tract 203; Autauga County; Alabama,1305,565,740,569,351,61,290,385,...,0.0,1.4,0.0,1.4,75.7,(X),(X),10.1,28.6,61.2
4,01001020400,Census Tract 204; Autauga County; Alabama,1666,948,718,1048,188,29,159,430,...,0.0,0.0,5.3,0.8,88.8,(X),(X),27.1,34.4,38.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85392,72153750501,Census Tract 7505.01; Yauco Municipio; Puerto ...,1661,1052,609,562,424,29,395,675,...,0.0,10.7,10.6,100.0,0.0,(X),(X),34.2,29.0,36.7
85393,72153750502,Census Tract 7505.02; Yauco Municipio; Puerto ...,895,394,501,266,331,68,263,298,...,0.0,16.5,15.8,100.0,0.0,(X),(X),42.0,32.0,26.0
85394,72153750503,Census Tract 7505.03; Yauco Municipio; Puerto ...,685,402,283,227,181,7,174,277,...,0.0,17.5,5.0,100.0,0.0,(X),(X),34.1,26.6,39.3
85395,72153750601,Census Tract 7506.01; Yauco Municipio; Puerto ...,1557,776,781,732,295,64,231,530,...,0.0,16.2,13.2,98.9,0.0,(X),(X),21.6,38.8,39.6
85396,72153750602,Census Tract 7506.02; Yauco Municipio; Puerto ...,898,686,212,437,139,12,127,322,...,0.0,24.5,8.0,100.0,0.0,(X),(X),43.8,44.3,11.9

In [72]:
# Save the DataFrame to a CSV file with the specified file path
file_path = 'phs1.csv'
filtered_df.to_csv('phs1.csv', index=False)

# Track the file location
print(f"Filtered data saved to: {'phs1.csv'}")

Filtered data saved to: phs1.csv

In [66]:
import pandas as pd

# Load the CSV files into DataFrames
philadelphia_df_filtered = pd.read_csv('phs.csv')
zip_pa_df = pd.read_csv('zip_pa.csv')

# Rename the 'GEOID' column to 'TRACT' in the philadelphia_df_filtered DataFrame
philadelphia_df_filtered.rename(columns={'GEOID': 'TRACT'}, inplace=True)

# Remove '1400000US' prefix from the 'TRACT' column in the zip_pa_df DataFrame
zip_pa_df['TRACT'] = zip_pa_df['TRACT'].str.replace('1400000US', '')

# Perform a left join on the 'TRACT' column
merged_df = pd.merge(philadelphia_df_filtered, zip_pa_df, on='TRACT', how='left')

# Display the merged DataFrame
print(merged_df)

AttributeError: Can only use .str accessor with string values!

NameError: name 'phs' is not defined

In [69]:
philadelphia_df_filtered = pd.read_csv('phs.csv')

In [70]:
philadelphia_df_filtered

,GEO_ID,NAME,S2201_C01_001E,S2201_C01_002E,S2201_C01_003E,S2201_C01_004E,S2201_C01_005E,S2201_C01_006E,S2201_C01_007E,S2201_C01_008E,...,S2201_C06_029E,S2201_C06_030E,S2201_C06_031E,S2201_C06_032E,S2201_C06_033E,S2201_C06_034E,S2201_C06_035E,S2201_C06_036E,S2201_C06_037E,S2201_C06_038E
0,1400000US42101000101,Census Tract 1.01; Philadelphia County; Pennsy...,1413,201,1212,268,56,15,41,1089,...,0.0,7.1,3.6,12.8,76.5,(X),(X),4.9,12.0,83.0
1,1400000US42101000102,Census Tract 1.02; Philadelphia County; Pennsy...,1960,265,1695,359,29,0,29,1572,...,0.0,2.5,1.4,5.3,84.0,(X),(X),6.7,11.3,82.0
2,1400000US42101000200,Census Tract 2; Philadelphia County; Pennsylvania,1686,412,1274,474,161,76,85,1051,...,0.0,0.0,6.1,7.2,51.7,(X),(X),12.9,2.6,84.5
3,1400000US42101000300,Census Tract 3; Philadelphia County; Pennsylvania,2347,923,1424,527,25,6,19,1795,...,0.0,2.5,12.7,7.2,53.3,(X),(X),17.5,26.7,55.9
4,1400000US42101000401,Census Tract 4.01; Philadelphia County; Pennsy...,1957,511,1446,331,76,50,26,1550,...,0.0,0.9,5.7,5.0,55.7,(X),(X),0.0,46.9,53.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,1400000US42101980905,Census Tract 9809.05; Philadelphia County; Pen...,0,0,0,0,0,0,0,0,...,-,-,-,-,-,(X),(X),-,-,-
404,1400000US42101980906,Census Tract 9809.06; Philadelphia County; Pen...,0,0,0,0,0,0,0,0,...,-,-,-,-,-,(X),(X),-,-,-
405,1400000US42101989100,Census Tract 9891; Philadelphia County; Pennsy...,0,0,0,0,0,0,0,0,...,-,-,-,-,-,(X),(X),-,-,-
406,1400000US42101989200,Census Tract 9892; Philadelphia County; Pennsy...,0,0,0,0,0,0,0,0,...,-,-,-,-,-,(X),(X),-,-,-
407,1400000US42101989300,Census Tract 9893; Philadelphia County; Pennsy...,0,0,0,0,0,0,0,0,...,-,-,-,-,-,(X),(X),-,-,-

In [78]:
import pandas as pd

# Read the CSV file into a DataFrame
phs1_df = pd.read_csv('phs1.csv')

# Display the DataFrame
print(phs1_df)

       ZIP        TRACT USPS_ZIP_PREF_STATE USPS_ZIP_PREF_CITY
0    19101  42101036902                  PA       PHILADELPHIA
1    19102  42101001101                  PA       PHILADELPHIA
2    19102  42101000806                  PA       PHILADELPHIA
3    19102  42101001204                  PA       PHILADELPHIA
4    19102  42101000300                  PA       PHILADELPHIA
..     ...          ...                 ...                ...
681  19160  42101989300                  PA       PHILADELPHIA
682  19172  42101001001                  PA       PHILADELPHIA
683  19176  42101980901                  PA       PHILADELPHIA
684  19181  42101000101                  PA       PHILADELPHIA
685  19192  42101000403                  PA       PHILADELPHIA

[686 rows x 4 columns]

In [97]:
replacement_tract = [x[2:] for x in phs1_df['TRACT'].astype(str)]

In [108]:
phs1_df["TRACT"] = pd.array(replacement_tract, int)
phs1_df

       ZIP      TRACT USPS_ZIP_PREF_STATE USPS_ZIP_PREF_CITY
0    19101  101036902                  PA       PHILADELPHIA
1    19102  101001101                  PA       PHILADELPHIA
2    19102  101000806                  PA       PHILADELPHIA
3    19102  101001204                  PA       PHILADELPHIA
4    19102  101000300                  PA       PHILADELPHIA
..     ...        ...                 ...                ...
681  19160  101989300                  PA       PHILADELPHIA
682  19172  101001001                  PA       PHILADELPHIA
683  19176  101980901                  PA       PHILADELPHIA
684  19181  101000101                  PA       PHILADELPHIA
685  19192  101000403                  PA       PHILADELPHIA

[686 rows x 4 columns]

In [115]:
merged_df = pd.merge(phs1_df, zip_pa, on='TRACT', how='outer')
merged_df

,ZIP_x,TRACT,USPS_ZIP_PREF_STATE_x,USPS_ZIP_PREF_CITY_x,Unnamed: 0,ZIP_y,USPS_ZIP_PREF_CITY_y,USPS_ZIP_PREF_STATE_y,RES_RATIO,BUS_RATIO,OTH_RATIO,TOT_RATIO
0,19116.0,17101401,PA,PHILADELPHIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,19113.0,45403701,PA,PHILADELPHIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,19153.0,45980000,PA,PHILADELPHIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,19115.0,91201501,PA,PHILADELPHIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,19138.0,91202401,PA,PHILADELPHIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1367,NaN,42101989300,NaN,NaN,32534.0,19120.0,PHILADELPHIA,PA,0.000210,0.003489,0.000000,0.000386
1368,NaN,42101989300,NaN,NaN,32593.0,19124.0,PHILADELPHIA,PA,0.000039,0.041802,0.013126,0.003698
1369,NaN,42101989300,NaN,NaN,32742.0,19134.0,PHILADELPHIA,PA,0.000244,0.033485,0.016173,0.003562
1370,NaN,42101989300,NaN,NaN,32818.0,19140.0,PHILADELPHIA,PA,0.000000,0.026776,0.008969,0.002245
1371,NaN,42101989300,NaN,NaN,33057.0,19160.0,PHILADELPHIA,PA,1.000000,1.000000,1.000000,1.000000

In [123]:
replacement_tract_pa = [x[2:] for x in zip_pa['TRACT'].astype(str)]

['1036902',
 '1001101',
 '1000806',
 '1001204',
 '1000300',
 '1000701',
 '1000901',
 '1000805',
 '1000403',
 '1000600',
 '1012501',
 '1000403',
 '1000805',
 '1000801',
 '1000803',
 '1000401',
 '1012502',
 '1000404',
 '1001201',
 '1001204',
 '1000702',
 '1001203',
 '1000300',
 '1000701',
 '1012501',
 '1010900',
 '1009000',
 '1036902',
 '1008601',
 '1980002',
 '1009200',
 '1008702',
 '1007800',
 '1008801',
 '1007700',
 '1010600',
 '1009100',
 '1009400',
 '1980003',
 '1010500',
 '1010700',
 '1008602',
 '1011000',
 '1007900',
 '1036901',
 '1008802',
 '1008701',
 '1010800',
 '1011100',
 '1000500',
 '1001001',
 '1000101',
 '1036700',
 '1001102',
 '1000102',
 '1000500',
 '1000902',
 '1036600',
 '1000200',
 '1000600',
 '1001002',
 '1000901',
 '1000200',
 '1037600',
 '1000600',
 '1000500',
 '1001102',
 '1001101',
 '1000902',
 '1037600',
 '1000600',
 '1000600',
 '1033800',
 '1039001',
 '1034100',
 '1030501',
 '1033600',
 '1030900',
 '1031000',
 '1030800',
 '1030700',
 '1034000',
 '1031102',
 '1030502',
 '1031101',
 '1034200',
 '1030600',
 '1033900',
 '1033500',
 '1980200',
 '1033702',
 '1003002',
 '1037300',
 '1036600',
 '1989200',
 '5403701',
 '1980300',
 '1035200',
 '1034600',
 '1034900',
 '1036202',
 '1034802',
 '1036201',
 '1034803',
 '1035302',
 '1035301',
 '1034801',
 '1035100',
 '1036203',
 '1034200',
 '1036000',
 '1980200',
 '1035601',
 '1035701',
 '1035602',
 '1201501',
 '1035500',
 '1035702',
 '1034501',
 '1034502',
 '1034400',
 '1036000',
 '1035800',
 '1035900',
 '7101401',
 '1036502',
 '1035701',
 '1035702',
 '1036501',
 '1036400',
 '1038800',
 '1025700',
 '1210400',
 '1210300',
 '1980100',
 '1025600',
 '1038600',
 '1038700',
 '1038400',
 '1023100',
 '1038500',
 '1025500',
 '1038800',
 '1023600',
 '1980100',
 '1025400',
 '1025200',
 '1038900',
 '1025300',
 '1025600',
 '1023700',
 '1038600',
 '1023500',
 '1028901',
 '1029100',
 '1027402',
 '1027401',
 '1027100',
 '1989300',
 '1027000',
 '1028800',
 '1030502',
 '1027300',
 '1028500',
 '1028700',
 '1028200',
 '1028600',
 '1029000',
 '1030501',
 '1027500',
 '1028902',
 '1027200',
 '1028400',
 '1015300',
 '1013800',
 '1016702',
 '1014900',
 '1013701',
 '1015101',
 '1016701',
 '1014700',
 '1015200',
 '1016800',
 '1014800',
 '1014000',
 '1013702',
 '1013900',
 '1016901',
 '1016902',
 '1015102',
 '1980001',
 '1014600',
 '1015700',
 '1014600',
 '1016600',
 '1016200',
 '1015600',
 '1014400',
 '1016100',
 '1016500',
 '1015300',
 '1014500',
 '1037700',
 '1014100',
 '1014100',
 '1013100',
 '1014201',
 '1036600',
 '1037600',
 '1036700',
 '1014400',
 '1014202',
 '1000102',
 '1013200',
 '1019000',
 '1038000',
 '1028901',
 '1989300',
 '1030200',
 '1029200',
 '1028902',
 '1019100',
 '1039002',
 '1030000',
 '1031900',
 '1039001',
 '1029400',
 '1032100',
 '1029800',
 '1030100',
 '1018300',
 '1029100',
 '1029900',
 '1031800',
 '1029300',
 '1038200',
 '1017900',
 '1014300',
 '1018001',
 '1015700',
 '1015800',
 '1016001',
 '1037800',
 '1016002',
 '1017701',
 '1014202',
 '1017800',
 '1017601',
 '1017702',
 '1014400',
 '1016300',
 '1016100',
 '1026700',
 '1027500',
 '1026800',
 '1027100',
 '1027000',
 '1026900',
 '1026600',
 '1027700',
 '1027200',
 '1021400',
 '1020900',
 '1021000',
 '1021500',
 '1021600',
 '1021600',
 '1980100',
 '1210300',
 '1021500',
 '1021200',
 '1021400',
 '1021100',
 '1021000',
 '1020900',
 '1021700',
 '1038400',
 '1021900',
 '1021800',
 '1022000',
 '1021300',
 '1980100',
 '1017201',
 '1017100',
 '1020800',
 '1020500',
 '1020600',
 '1017000',
 '1020702',
 '1020701',
 '1020200',
 '1013800',
 '1012501',
 '1013401',
 '1014000',
 '1012502',
 '1037600',
 '1013601',
 '1980001',
 '1013701',
 '1013402',
 '1013500',
 '1013900',
 '1013602',
 '1013300',
 '1013702',
 '1012201',
 '1009500',
 '1011800',
 '1011900',
 '1012204',
 '1012000',
 '1011200',
 '1018400',
 '1010400',
 '1010300',
 '1011300',
 '1980002',
 '1010500',
 '1011700',
 '1011400',
 '1037500',
 '1012100',
 '1012203',
 '1010200',
 '1011100',
 '1015200',
 '1016702',
 '1016901',
 '1020101',
 '1980001',
 '1016600',
 '1016800',
 '1017300',
 '1020200',
 '1017400',
 '1017202',
 '1017201',
 '1016701',
 '1017000',
 '1016902',
 '1020000',
 '1017100',
 '1016200',
 '1019900',
 '1016600',
 '1017602',
 '1016100',
 '1017601',
 '1019501',
 '1020000',
 '1016500',
 '1016300',
 '1017500',
 '1016400',
 '1017400',
 '1018801',
 '1037800',
 '1017701',
 '1018802',
 '1017800',
 '1019501',
 '1018002',
 '1019200',
 '1019000',
 '1017601',
 '1989300',
 '1017702',
 '1019100',
 '1038200',
 '1037900',
 '1019502',
 '1017900',
 '1018001',
 '1017602',
 '1031600',
 '1032600',
 '1031501',
 '1038100',
 '1032100',
 '1033000',
 '1032000',
 '1032300',
 '1031700',
 '1031900',
 '1032500',
 '1038100',
 '1032900',
 '1033102',
 '1033200',
 '1033101',
 '1989100',
 '1034801',
 '1980200',
 '1031501',
 '1034702',
 '1034900',
 '1033000',
 '1029900',
 '1038200',
 '1029800',
 '1018300',
 '1018400',
 '1038100',
 '1037900',
 '1038000',
 '1037800',
 '1026400',
 '1026302',
 '1026700',
 '1202401',
 '1026600',
 '1038900',
 '1025200',
 '1027700',
 '1026500',
 '1024900',
 '1024700',
 '1027901',
 '1024800',
 '1027902',
 '1009400',
 '1010500',
 '1980800',
 '1009500',
 '1008301',
 '1008400',
 '1008302',
 '1008701',
 '1008601',
 '1008602',
 '1010000',
 '1009600',
 '1009300',
 '1010300',
 '1009200',
 '1010200',
 '1010400',
 '1008500',
 '1019800',
 '1017100',
 '1028400',
 '1989300',
 '1028300',
 '1019700',
 '1020000',
 '1980500',
 '1038301',
 '1020200',
 '1020102',
 '1019900',
 '1017601',
 '1020500',
 '1028000',
 '1019502',
 '1020300',
 '1028700',
 '1020400',
 '1028100',
 '1020101',
 '1028800',
 '1019501',
 '1017300',
 '1017500',
 '1028200',
 '1027800',
 '1028000',
 '1027901',
 '1028300',
 '1027700',
 '1027902',
 '1026800',
 '1028400',
 '1028100',
 '1027000',
 '1027600',
 '1980901',
 '1006400',
 '1006700',
 '1006600',
 '1006300',
 '1006200',
 '1006000',
 '1006100',
 '1006500',
 '1005500',
 '1007300',
 '1007000',
 '1008400',
 '1007900',
 '1039100',
 '1008601',
 '1006600',
 '1008200',
 '1007101',
 '1007102',
 '1007400',
 '1008301',
 '1008101',
 '1008302',
 '1008500',
 '1007200',
 '1980901',
 '1007700',
 '1007800',
 '1008102',
 '1006500',
 '1008000',
 '1006700',
 '1038900',
 '1020500',
 '1028000',
 '1023700',
 '1025200',
 '1024300',
 '1024100',
 '1024700',
 '1020800',
 '1023800',
 '1027902',
 '1024000',
 '1023500',
 '1023900',
 '1023600',
 '1024800',
 '1024500',
 '1024200',
 '1980100',
 '1024600',
 '1024400',
 '1020600',
 '1003901',
 '1003702',
 '1003800',
 '1003300',
 '1980906',
 '1980600',
 '1980904',
 '1004002',
 '1037300',
 '1003902',
 '1003600',
 '1003701',
 '1980902',
 '1003200',
 '1980905',
 '1989200',
 '1980903',
 '1002900',
 '1004001',
 '1003002',
 '1003100',
 '1003001',
 '1002300',
 '1002900',
 '1001900',
 '1001203',
 '1002400',
 '1002200',
 '1001301',
 '1001204',
 '1001201',
 '1002000',
 '1001400',
 '1003002',
 '1980902',
 '1001500',
 '1003300',
 '1980903',
 '1001302',
 '1003100',
 '1001800',
 '1002100',
 '1003200',
 '1002500',
 '1036600',
 '1001800',
 '1001102',
 '1001500',
 '1002702',
 '1002802',
 '1002300',
 '1001700',
 '1001002',
 '1002400',
 '1002900',
 '1001101',
 '1001600',
 '1001001',
 '1002701',
 '1002801',
 '1004101',
 '1004202',
 '1004201',
 '1002801',
 '1980701',
 '1980702',
 '1037300',
 '1002702',
 '1004001',
 '1002802',
 '1004104',
 '1004002',
 '1002900',
 '1002701',
 '1980600',
 '1004103',
 '1037200',
 '1031700',
 '1031000',
 '1030900',
 '1031401',
 '1039002',
 '1033500',
 '1039001',
 '1033400',
 '1033200',
 '1033101',
 '1031300',
 '1031600',
 '1031502',
 '1031200',
 '1031402',
 '1031101',
 '1031501',
 '1031102',
 '1031800',
 '1026302',
 '1025400',
 '1026301',
 '1025600',
 '1202401',
 '1025900',
 '1026200',
 '1025800',
 '1038900',
 '1210500',
 '1026000',
 '1026100',
 '1026400',
 '1025500',
 '1011500',
 '1011400',
 '1009500',
 '1980800',
 '1011200',
 '1010100',
 '1010000',
 '1009600',
 '1009801',
 '1011300',
 '1037500',
 '1009802',
 '1033400',
 '1033200',
 '1033702',
 '1034702',
 '1033500',
 '1980200',
 '1033300',
 '1034701',
 '1033701',
 '1033600',
 '1980901',
 '1006000',
 '1005600',
 '1005500',
 '1005400',
 '1980400',
 '1006700',
 '5980000',
 '1980300',
 '1036202',
 '1036201',
 '1036203',
 '1036400',
 '1036301',
 '1036302',
 '1036303',
 '1036000',
 '1036100',
 '1989300',
 '1001001',
 '1980901',
 '1000101',
 '1000403']

In [134]:
phs1_df

       ZIP      TRACT USPS_ZIP_PREF_STATE USPS_ZIP_PREF_CITY
0    19101  101036902                  PA       PHILADELPHIA
1    19102  101001101                  PA       PHILADELPHIA
2    19102  101000806                  PA       PHILADELPHIA
3    19102  101001204                  PA       PHILADELPHIA
4    19102  101000300                  PA       PHILADELPHIA
..     ...        ...                 ...                ...
681  19160  101989300                  PA       PHILADELPHIA
682  19172  101001001                  PA       PHILADELPHIA
683  19176  101980901                  PA       PHILADELPHIA
684  19181  101000101                  PA       PHILADELPHIA
685  19192  101000403                  PA       PHILADELPHIA

[686 rows x 4 columns]

In [144]:
import pandas as pd

# Read the CSV files into DataFrames
phs1_df = pd.read_csv('phs1.csv')
zip_pa_df = pd.read_csv('zip_pa.csv')

# Remove the first two characters from the 'TRACT' column in phs1_df
phs1_df['TRACT'] = phs1_df['TRACT'].str[2:]

# Convert 'TRACT' column in zip_pa_df to string type
zip_pa_df['TRACT'] = zip_pa_df['TRACT'].astype(str)

# Perform the join on the modified 'TRACT' column
joined_df = phs1_df.join(zip_pa_df.set_index('TRACT'), on='TRACT', rsuffix='_zip_pa')

# Display the joined DataFrame
print(joined_df)

AttributeError: Can only use .str accessor with string values!

In [141]:
phs1_df

       ZIP        TRACT USPS_ZIP_PREF_STATE USPS_ZIP_PREF_CITY
0    19101  42101036902                  PA       PHILADELPHIA
1    19102  42101001101                  PA       PHILADELPHIA
2    19102  42101000806                  PA       PHILADELPHIA
3    19102  42101001204                  PA       PHILADELPHIA
4    19102  42101000300                  PA       PHILADELPHIA
..     ...          ...                 ...                ...
681  19160  42101989300                  PA       PHILADELPHIA
682  19172  42101001001                  PA       PHILADELPHIA
683  19176  42101980901                  PA       PHILADELPHIA
684  19181  42101000101                  PA       PHILADELPHIA
685  19192  42101000403                  PA       PHILADELPHIA

[686 rows x 4 columns]

In [153]:
phs1_df.describe()

                ZIP         TRACT
count    686.000000  6.860000e+02
mean   19131.247813  4.210070e+10
std       15.005492  4.489801e+06
min    19101.000000  4.201710e+10
25%    19120.000000  4.210101e+10
50%    19132.500000  4.210102e+10
75%    19144.000000  4.210103e+10
max    19192.000000  4.210199e+10

In [149]:
zip_pa['TRACT'].str[4:]

32376    902
32377    101
32378    806
32379    204
32380    300
        ...
33057    300
33058    001
33059    901
33060    101
33061    403
Name: TRACT, Length: 686, dtype: string

In [166]:
phs_df = pd.read_csv('phs.csv')

In [170]:
phs_df['GEO_ID_new'] = phs_df['GEO_ID'].str[-7:]

In [172]:
df_joined = phs_df.merge(zip_pa, right_on = 'TRACT', left_on = 'GEO_ID_new', how = 'left')

In [188]:
df_final = df_joined[[
    'ZIP', 
    'S2201_C01_001E', 
    'S2201_C01_013E', 
    'S2201_C03_001E', 
    'S2201_C01_009E',
    'S2201_C01_021E'
    # 'S2201_C04_001E'
]].groupby('ZIP').mean()

In [194]:
df_final = df_final.rename(columns={'S2201_C01_001E': 'Tot_HH',
                                    'S2201_C01_009E': 'Tot_HH_U18',
                                    'S2201_C01_013E': 'Tot_HH_U18_fem',
                                    'S2201_C03_001E': 'HH_SNAP',
                                    'S2201_C01_021E': 'Tot_HH_Upov'
                                   })
df_final.to_csv('df_final.csv', index=False)

In [182]:
# df_joined.groupby('ZIP').agg({'S2201_C01_001E':'mean', 'S2201_C03_001E':'mean' , 'S2201_C01_009E':'mean'})

In [193]:

import matplotlib.pyplot as plt

# Assuming you have a DataFrame named 'data_df' with columns 'ZIP' and 'Value'
# 'ZIP' represents ZIP codes and 'Value' represents the data you want to visualize
# Adjust the column names as per your actual DataFrame structure

# Create a pivot table to prepare the data for the heatmap
heatmap_data = df_final.pivot_table(values='ZIP', index='ZIP', columns='Tot_HH')

# Create the heatmap using seaborn
plt.figure(figsize=(10, 8))
sns.heatmap(heatmap_data, cmap='viridis', annot=True, fmt=".1f", linewidths=.5)
plt.title('Heatmap of Data Across ZIP Codes and Tracts')
plt.xlabel('ZIP Code')
plt.ylabel('Tot_HH')
plt.show()

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in ./.local/lib/python3.10/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in ./.local/lib/python3.10/site-packages (from seaborn) (1.26.4)
Requirement already satisfied: pandas>=1.2 in ./.local/lib/python3.10/site-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /opt/tljh/user/lib/python3.10/site-packages (from seaborn) (3.8.1)
Requirement already satisfied: contourpy>=1.0.1 in /opt/tljh/user/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /opt/tljh/user/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/tljh/user/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.43.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/tljh/user/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /opt/tljh/user/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (23.2)
Requirement already satisfied: pillow>=8 in /opt/tljh/user/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/tljh/user/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /opt/tljh/user/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/tljh/user/lib/python3.10/site-packages (from pandas>=1.2->seaborn) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in ./.local/lib/python3.10/site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: six>=1.5 in /opt/tljh/user/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)

KeyError: 'ZIP'

In [ ]:
# Generate sample data (replace this with your actual data)
data = {
    'Metric1': [10, 20, 30, 40, 50],
    'Metric2': [15, 25, 35, 45, 55]
}
data_df = pd.DataFrame(data)

# Create a scatter plot using seaborn
plt.figure(figsize=(8, 6))
sns.scatterplot(data=data_df, x='Metric1', y='Metric2')
plt.title('Scatter Plot of Metric1 vs Metric2')
plt.xlabel('Metric1')
plt.ylabel('Metric2')
plt.grid(True)
plt.show()

In [ ]:
install plotly
import plotly.express as px
df = px.data.gapminder()

fig = px.scatter(df.query("year==2007"), x="gdpPercap", y="lifeExp",
	         size="pop", color="continent",
                 hover_name="country", log_x=True, size_max=60)
fig.show()